from textual.theme import Theme


def _theme(
    name: str,
    *,
    canvas: str,
    main: str,
    rail: str,
    elevated: str,
    text: str,
    secondary: str,
    muted: str,
    border: str,
    primary: str,
    active: str,
    success: str,
    warning: str,
    error: str,
    info: str,
) -> Theme:
    return Theme(
        name=name,
        primary=primary,
        secondary=info,
        accent=active,
        foreground=text,
        background=canvas,
        surface=main,
        panel=rail,
        success=success,
        warning=warning,
        error=error,
        dark=True,
        variables={
            "surface-canvas": canvas,
            "surface-main": main,
            "surface-rail": rail,
            "surface-elevated": elevated,
            "text-primary": text,
            "text-secondary": secondary,
            "text-muted": muted,
            "border-subtle": border,
            "accent-primary": primary,
            "accent-active": active,
            "status-success": success,
            "status-warning": warning,
            "status-error": error,
            "status-info": info,
        },
    )


THEMES = {
    "ember": _theme(
        "ember",
        canvas="#1a100b",
        main="#1f1510",
        rail="#261c16",
        elevated="#2e221a",
        text="#f1eadf",
        secondary="#c4a88a",
        muted="#7a6a5a",
        border="#3d3026",
        primary="#e06c3b",
        active="#f08a54",
        success="#87a96b",
        warning="#d5a94f",
        error="#d9685f",
        info="#6f9fba",
    ),
    "cyber": _theme(
        "cyber",
        canvas="#0a0a14",
        main="#0f0f1a",
        rail="#141428",
        elevated="#1a1a36",
        text="#e0e0ff",
        secondary="#8888cc",
        muted="#555577",
        border="#2a2a4a",
        primary="#00ffcc",
        active="#33ffdd",
        success="#00cc88",
        warning="#ffcc00",
        error="#ff3366",
        info="#3388ff",
    ),
    "forest": _theme(
        "forest",
        canvas="#0f1a10",
        main="#141f15",
        rail="#1a261b",
        elevated="#202e22",
        text="#e0f0e0",
        secondary="#88aa88",
        muted="#557755",
        border="#2a3a2a",
        primary="#44cc44",
        active="#66ee66",
        success="#44cc44",
        warning="#ccaa00",
        error="#cc4444",
        info="#4488cc",
    ),
    "ocean": _theme(
        "ocean",
        canvas="#0a141e",
        main="#0f1a26",
        rail="#14202e",
        elevated="#1a2838",
        text="#ddeeff",
        secondary="#88aacc",
        muted="#556688",
        border="#2a3a4a",
        primary="#44aadd",
        active="#66ccff",
        success="#44cc88",
        warning="#ddaa44",
        error="#dd4444",
        info="#4488dd",
    ),
    "solarized": _theme(
        "solarized",
        canvas="#002b36",
        main="#073642",
        rail="#0b3f4a",
        elevated="#124b57",
        text="#fdf6e3",
        secondary="#93a1a1",
        muted="#657b83",
        border="#285763",
        primary="#2aa198",
        active="#40c7bd",
        success="#859900",
        warning="#b58900",
        error="#dc322f",
        info="#268bd2",
    ),
    "matrix": _theme(
        "matrix",
        canvas="#050b06",
        main="#09120b",
        rail="#0d1a10",
        elevated="#132519",
        text="#d8f3dc",
        secondary="#95d5b2",
        muted="#52765e",
        border="#1e4d2b",
        primary="#52b788",
        active="#74c69d",
        success="#40c463",
        warning="#d4b942",
        error="#e05d5d",
        info="#56a3a6",
    ),
    "dusk": _theme(
        "dusk",
        canvas="#171322",
        main="#1e192b",
        rail="#262034",
        elevated="#30283f",
        text="#f1e9f7",
        secondary="#c6abc9",
        muted="#806f8b",
        border="#493c59",
        primary="#c586c0",
        active="#e1a6d7",
        success="#8fbc8f",
        warning="#d7b46a",
        error="#df6f78",
        info="#7aa2d6",
    ),
    "high-contrast": _theme(
        "high-contrast",
        canvas="#000000",
        main="#080808",
        rail="#111111",
        elevated="#1c1c1c",
        text="#ffffff",
        secondary="#e6e6e6",
        muted="#a8a8a8",
        border="#ffffff",
        primary="#00ffff",
        active="#ffff00",
        success="#5cff5c",
        warning="#ffd700",
        error="#ff5f5f",
        info="#66b3ff",
    ),
    "mono": _theme(
        "mono",
        canvas="#0d0d0d",
        main="#141414",
        rail="#1a1a1a",
        elevated="#222222",
        text="#e8e8e8",
        secondary="#999999",
        muted="#555555",
        border="#2a2a2a",
        primary="#aaaaaa",
        active="#cccccc",
        success="#888888",
        warning="#999999",
        error="#aaaaaa",
        info="#777777",
    ),
}

DEFAULT_THEME = "ember"
